name: card_selector
description: Widget selector for Flutter using stack. The selector is fully configurable, animation time, gap between cards, size factor for stacxked cards, ...
version: 0.1.0
author: Victor Bonnet<victor.bonnet@gmail.com>
homepage: https://github.com/victorbonnet/flutter_card_selector

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
